FROM python:3.13.5-slim-bookworm
WORKDIR /code
COPY pipeline_v2.bin .

FROM agrigorev/zoomcamp-model:2025

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV PATH="/app/.venv/bin:$PATH"

COPY ".python-version" "pyproject.toml"  "uv.lock"  ./

RUN uv sync --locked

COPY "predict.py" "pipeline_v1.bin"  ./

EXPOSE 9696

ENTRYPOINT [ "uvicorn", "predict:app", "--host", "0.0.0.0", "--port", "9696"]
